<?php

namespace Atos\MissionRecensementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DomaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomaineRepository extends EntityRepository
{

    public function getRoots()
    {
        $qb = $this->createQueryBuilder("d");
        
        $qb->where($qb->expr()->isNull("d.domaineParent"));
        $qb->orderBy("d.nom");
        
        return $qb;
    }

    public function getNonRoots()
    {
        $qb = $this->createQueryBuilder("d");
        
        $qb->where($qb->expr()->isNotNull("d.domaineParent"));
        $qb->orderBy("d.nom");
        
        return $qb;
    }
}
