<?php

namespace Atos\MissionRecensementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpecialiteMetierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialiteMetierRepository extends EntityRepository
{
}
