<?php

namespace Atos\MissionRecensementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypePrestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePrestationRepository extends EntityRepository
{
}
